# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

Options:
    release-build: True
    use-ccache: True
    use-asan: False
    run-gcovr: False
    per-test-timeout: 4:00
    cmake-options: '-DHIDE_SAFE_ASSERTS=OFF -DBUILD_TESTING=ON -DKRITA_ENABLE_PCH=OFF'
    tests-run-in-parallel: True
    ccache-large-cache: True
